### ISSUE TITLE
Remove the LaTeX output of your thesis

### ISSUE THREAD

**Issue by palazzem** [mariotsi/Bachelor-Thesis#1]
Usually all repositories should contain only the source code of your project/documentation. In your case, you're providing the output to easily produce a downloadable link for your PDF.
Even if it's ok for the sake of your thesis, remember to remove them from the version control after your discussion:
- remove all output files and make a commit
- add these files (just the wildcards) in your .gitignore and commit

**Comment by mariotsi** [comment]
Removed the PDF file as suggested on commit 380b0d55e1dbf6430a0fc858dad7bc9f156ceb37
